# Generated by Django 4.2.5 on 2025-02-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_remove_task_user_alter_task_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank='FALSE', null='FALSE'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(blank='FALSE', max_length=255, null='FALSE'),
        ),
    ]
